# Generated by Django 2.2 on 2020-08-10 05:48

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200808_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='tel',
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='head',
            field=models.ImageField(blank=True, help_text='头像', null=True, upload_to='upload', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
